kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-user
  namespace: webapps
  labels:
    app: nodejs-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-user
  template:
    metadata:
      labels:
        app: nodejs-user
    spec:
      containers:
        - name: nodejs-user
          image: "lachisenarath576259/userservice"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-user
  namespace: webapps
spec:
  selector:
    app: nodejs-user
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 3001
      port: 80
